#Following https://tavareshugo.github.io/data-carpentry-rnaseq/00_exercises.html#31_examine_prcomp()_output

if (!requireNamespace('BiocManager', quietly = TRUE))
  install.packages('BiocManager')

BiocManager::install("tidyverse")
BiocManager::install("ggplot2")
#BiocManager::install("ggrepel")
BiocManager::install("viridis")

library(tidyverse)
library(ggplot2)
#library(ggrepel)
library(viridis)

#Create a matrix from our table of counts
pca_matrix <- read_tsv("~/Desktop/STAR_stringtie/TPM_matrix.txt") %>%
#Add one to all TPM values
mutate(across(where(is.numeric),~ .x + 1)) %>%
#Log-transform the TPM+1 values
mutate(across(where(is.numeric),log2)) %>%
#Transpose the counts table so the "gene" column becomes the rownames
column_to_rownames("genes") %>%
#Coerce into a matrix
as.matrix() %>%
#Transpose the matrix so that rows=samples and columns=variables
t()
#Check for #N/A and non-numeric values
all(is.finite(pca_matrix))

#Perform the PCA
sample_pca <- prcomp(pca_matrix)

#Check output of prcomp
pca_matrix[1:10, 1:5]

#Class of the object
class(sample_pca)

#Structure of the object
str(sample_pca)

# "sdev" contains the standard deviation explained by each PC, so if we square it we get the eigenvalues (or explained variance)
# "rotation" contains the variable loadings for each PC, which define the eigenvectors
# "x" contains the PC scores, i.e. the data projected on the new PC axis
# "center" in this case contains the mean of each gene, which was subtracted from each value
# "scale" contains the value FALSE because we did not scale the data by the standard deviation

# eigenvalues squared
pc_eigenvalues <- sample_pca$sdev^2

#Variable loadings
pc_loadings <- sample_pca$rotation

ncol(pc_scores)
length(pc_eigenvalues)
ncol(pc_loadings)

#PC scores
pc_scores <- sample_pca$x

#Variance explained by PCs
#Convert matrix to tibble object in order to make a plot in ggplot2
# create a "tibble" manually with 
# a variable indicating the PC number
# and a variable with the variances
pc_eigenvalues <- tibble(PC = factor(1:length(pc_eigenvalues)), 
                         variance = pc_eigenvalues) %>% 
  # add a new column with the percent variance
  mutate(pct = variance/sum(variance)*100) %>% 
  # add another column with the cumulative variance explained
  mutate(pct_cum = cumsum(pct))

#Print the result
pc_eigenvalues

#Produce a Scree Plot to show the fraction of the total variance explained by each PC
pc_eigenvalues %>% 
  ggplot(aes(x = PC)) +
  geom_col(aes(y = pct)) +
  geom_line(aes(y = pct_cum, group = 1)) + 
  geom_point(aes(y = pct_cum)) +
  labs(x = "Principal component", y = "Fraction variance explained")

# The PC scores are stored in the "x" value of the prcomp object
pc_scores <- sample_pca$x
pc_scores <- pc_scores %>% 
#Convert to a tibble retaining the sample names as a new column
as_tibble(rownames = "sample")

#Print the result
pc_scores

#Load sample info i.e. metadata 
sample_info <- read_tsv("~/Desktop/STAR_stringtie/sample_info.txt")

#Extract the loadings from prcomp
pca_plot1 <- sample_pca$x %>% 
#Convert to a tibble retaining the sample names as a new column
as_tibble(rownames = "sample") %>% 
#Join with "sample_info" table
full_join(sample_info, by = "sample") %>% 
#Create the plot
ggplot(aes(x=PC1, y=PC2)) +
geom_point(aes(colour=stage,shape=sex,alpha=20),size=5) +
#geom_text_repel(aes(label=replicate), point.padding=0.8, size=3, box.padding = 0.3, min.segment.length=1, max.overlaps=Inf) +
scale_colour_discrete(breaks=c("Eggs","Miracidia","1d_Sporocysts","5d_Sporocysts","32d_Sporocysts","Cercariae","2d_Somules","Juveniles")) +
labs(y="PC2 (23.7%)",x="PC1 (36.6%)") +
theme (panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  panel.background=element_blank(),
  legend.key = element_blank(),
  axis.line = element_line(colour = "gray")) +
scale_alpha(guide = 'none') +
scale_colour_viridis_d()

#Print and save the plot
pca_plot1
ggsave("~/Desktop/plot.pdf", height=7, width=7, units="in")

